version: "3.8"
services:
  auth-service:
    build: ./auth-service
    ports:
      - 4000:4000
    environment:
      SECRET: ${SECRET}
      MONGODB_AUTH_SERVICE_URL: ${MONGODB_AUTH_SERVICE_URL}
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
